### PR TITLE
Add swiping capability to facilitate more tactilely pleasing snap judgements

### PR DESCRIPTION
**Pull request by LucyMcGowan**
- added swipe capability
- added a counter due to different behavior of swiper vs buttons to facilitate leveling up
- changed how app initiates due to different behavior of swiper

### CODE REVIEW

**Comment by jtleek** [comment]
Ok first of all you two are freaking awesome for doing this! 

Second of all - I'm having trouble getting the swipe to work. The app loads and everything but I can't "swipe" will it only work on mobile?

**Comment by LucyMcGowan** [comment]
yikes! It works on my laptop -- the "swipe region" is over the abstract -- is that where you are swiping?

**Comment by jtleek** [comment]
How many fingers were you using to swipe?

**Comment by LucyMcGowan** [comment]
One finger click & drag

**Comment by jtleek** [comment]
Ah! That works. Holy crap this is awesome!!!!

Have you tried it on mobile yet?

Can you do a few things to add to the pull request: (1) add yourselves as
authors of the app on the about page with links to your websites, (2) add
some swiping instructions to the main page (maybe right above where the
paper is displayed it should say "click and swipe abstract to rate" or
something? (3) change the instructions on the help page to reflect this new
functionality?

Then I'll merge and push it to the papr website.

**Comment by LucyMcGowan** [comment]
Yes! The swiping works on mobile, but if the abstract is too long you can't scroll -- I'm sure we can come up with a solution for that though.

Will do!

**Comment by jtleek** [comment]
Just waiting on this pull request until you folks give yourself credit etc. :)

**Comment by LucyMcGowan** [comment]
we got hung up looking for swipe icons :) maybe we can add later..

**Comment by jtleek** [comment]
If you add them later I'll merge that in too. I'm going to pusht he new
version tomorrow morning and then announce it on twitter ok?

**Comment by LucyMcGowan** [comment]
awesome -- thanks!

**Comment by LucyMcGowan** [comment]
I swapped out an icon to demonstrate swiping (demo: https://lucy.shinyapps.io/papr_swiper/) -- if you like it we can merge that in (I could go either way).

**Pull request merged**
